name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download JDK
        id: downloadJdk
        uses: oracle-actions/setup-java@v1
        with:
          website: jdk.java.net
          release: 19
          install: false # Suppress automatic delegation to `actions/setup-java`

      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ steps.downloadJdk.outputs.version }}
          distribution: jdkfile
          jdkFile: ${{ steps.downloadJdk.outputs.archive }}
          #cache: maven

      - name: Build project
        run: |
          ./mvnw \
              --batch-mode \
              --debug \
              --errors \
              --show-version \
              -Dmaven.resolver.transport=wagon \
              -Dmaven.wagon.httpconnectionManager.ttlSeconds=180 \
              verify
